export const UI_TEXTS = {
  app: {
    heroTitle: 'Mapeador visual de schemas JSON',
    heroCopy:
      'Organize a entrada e a saída em uma experiência visual simples: arraste da esquerda para o centro e use a lateral direita apenas para refinamentos.',
    saveButton: 'Salvar na API',
    loadButton: 'Carregar última configuração',
    savedFileLabel: 'Arquivo salvo:',
    partnerLabel: 'Codigo do parceiro',
    partnerHelp: 'Nome que identifica este cadastro na operação.',
    eventLabel: 'Evento',
    eventHelp: 'Evento ou etapa da operação associada a este cadastro.',
    schemaTypeLabel: 'Tipo do schema',
    schemaTypeHelp: 'Define como este cadastro será identificado na API.',
    versionLabel: 'Versão',
    versionHelp: 'Versão funcional desta configuração.',
    previewLauncher: 'Abrir painel',
    previewModalTitle: 'Painel de conferência',
    previewModalCopy: 'Confira o resultado final, revise alertas e exporte o JSON em um painel limpo e focado.',
    previewModalClose: 'Fechar preview',
    flowStep1Title: '1. Arraste da origem',
    flowStep1Copy: 'Comece pelo painel da esquerda e escolha o dado que deseja aproveitar.',
    flowStep2Title: '2. Solte no destino',
    flowStep2Copy: 'Solte direto no destino para montar a estrutura sem etapas extras.',
    flowStep3Title: '3. Refine se precisar',
    flowStep3Copy: 'Use a lateral direita apenas quando precisar completar ou refinar o comportamento do campo.'
  },
  source: {
    panelTitle: 'Dados de entrada',
    panelCopy: 'Importe o JSON ou monte a estrutura manualmente.',
    importTitle: 'Importar schema de origem',
    importCopy: 'Escolha um arquivo JSON para preencher este painel automaticamente.',
    importAction: 'Selecionar arquivo JSON',
    templateAction: 'Baixar template de origem',
    editorTitle: 'JSON técnico',
    editorCopy: 'Veja o JSON carregado em modo leitura ou edite manualmente quando precisar.',
    editorAction: 'Aplicar texto manualmente',
    viewerMode: 'Viewer',
    editorMode: 'Editar',
    viewerEmpty: 'Nenhum schema de origem carregado ainda.',
    editorFootnote: 'Este painel começa vazio e recebe estrutura apenas quando você importa ou aplica um JSON válido.',
    noFile: 'Nenhum arquivo importado ainda',
    clearFile: 'Limpar informações',
    noMatches: 'Nenhum campo encontrado com os filtros atuais.',
    searchCount: 'resultado(s)',
    searchPlaceholder: 'Buscar campo, caminho ou grupo...',
    visibleFields: 'campos visíveis',
    usedFields: 'campos em uso',
    typeLabel: 'Tipo do campo',
    clearFilters: 'Limpar',
    expandAll: 'Expandir tudo',
    collapseAll: 'Recolher tudo',
    addField: '+ Campo',
    addObject: '+ Objeto',
    addArray: '+ Array',
    removeSelected: 'Excluir selecionado',
    manualGuideTitle: 'Como montar a entrada manualmente',
    manualGuideStep1: 'Selecione o ponto onde a nova estrutura deve entrar.',
    manualGuideStep2: 'Use + Campo, + Objeto ou + Array para criar a estrutura.',
    manualGuideStep3: 'Ao criar um array, o item-modelo [item] aparece automaticamente logo abaixo.',
    manualGuideStep4: 'Crie os campos dentro de [item] quando quiser representar cada item da lista.'
  },
  target: {
    panelTitle: 'Estrutura de saída',
    panelCopy: 'Monte a estrutura final e solte os campos da origem para preencher cada parte.',
    importTitle: 'Importar schema de destino',
    importCopy: 'Escolha um arquivo JSON para preencher este painel automaticamente.',
    importAction: 'Selecionar arquivo JSON',
    templateAction: 'Baixar template de destino',
    editorTitle: 'JSON técnico',
    editorCopy: 'Veja o JSON carregado em modo leitura ou edite manualmente quando precisar.',
    editorAction: 'Aplicar texto manualmente',
    viewerMode: 'Viewer',
    editorMode: 'Editar',
    viewerEmpty: 'Nenhum schema de destino carregado ainda.',
    editorFootnote: 'Este painel começa vazio e recebe estrutura apenas quando você importa ou aplica um JSON válido.',
    noFile: 'Nenhum arquivo importado ainda',
    clearFile: 'Limpar informações',
    noMatches: 'Nenhum nó de destino combina com a busca atual.',
    searchCount: 'resultado(s)',
    searchPlaceholder: 'Buscar campo de saída...',
    visibleNodes: 'nós visíveis',
    mappedFields: 'campos ligados',
    emptyFields: 'sem ligação',
    withError: 'com alerta',
    typeLabel: 'Tipo do campo',
    clearFilters: 'Limpar',
    expandAll: 'Expandir tudo',
    collapseAll: 'Recolher tudo',
    addField: '+ Campo',
    addObject: '+ Objeto',
    addArray: '+ Array',
    removeSelected: 'Excluir selecionado',
    manualGuideTitle: 'Como montar a saída manualmente',
    manualGuideStep1: 'Selecione o ponto onde a nova estrutura deve entrar.',
    manualGuideStep2: 'Use + Campo, + Objeto ou + Array para criar a estrutura final.',
    manualGuideStep3: 'Se o nó for um array, indique abaixo de qual lista da origem ele deve nascer.',
    manualGuideStep4: 'Depois crie os campos dentro do [item] e ligue cada um deles aos dados da origem.',
    idleDropBanner: 'Selecione ou edite a estrutura e solte os campos da origem no destino desejado.',
    activeDropBannerPrefix: 'Arraste',
    activeDropBannerSuffix: 'para qualquer nó de destino.'
  },
  workbench: {
    panelTitle: 'Refino do campo',
    panelCopy:
      'O fluxo principal continua sendo arrastar da origem para o destino. Use esta lateral apenas para ajustes pontuais.',
    flowTitle: 'Como usar com fluidez',
    flowItem1: 'Arraste um campo da esquerda para o ponto desejado no destino.',
    flowItem2: 'Selecione o campo de destino para revisar como ele será preenchido.',
    flowItem3: 'Abra os atalhos abaixo só se quiser sugestões, automapeamento ou ligações complementares.',
    emptyReview: 'sem ligação',
    visualGenerators: 'com regra visual',
    errors: 'com alerta',
    reviewHelp: 'Resumo rápido do estado atual.',
    selectedField: 'Campo selecionado para refinamento.',
    selectedContainer: 'Container selecionado para receber novos itens ou ligações.',
    configuredFields: 'campos configurados',
    visualRuleInfoPrefix: 'Este campo recebe',
    visualRuleInfoMiddle: 'regra(s) visual(is). Ao salvar, isso vira',
    visualRuleInfoSuffix: 'automaticamente',
    assistantsTitle: 'Ajuda opcional',
    assistantsCopy: 'Atalhos para sugestões, automapeamento e ligações complementares.',
    assistantsOpen: 'Abrir assistentes',
    assistantsClose: 'Esconder assistentes',
    bestSuggestion: 'Aplicar melhor sugestão',
    autoMap: 'Preencher campos vazios',
    suggestionsTitle: 'Sugestões rápidas',
    linkBuilderTitle: 'Ligação manual',
    linkBuilderCopy: 'Use apenas quando quiser buscar, digitar um caminho ou montar uma ligação específica.',
    manualSearchLabel: 'Buscar em toda a origem',
    manualSearchPlaceholder: 'Buscar por nome, caminho ou tipo',
    sourceFocus: 'Origem escolhida',
    targetSelected: 'Destino selecionado',
    emptyFocusedSource: 'Escolha ou arraste um campo da origem',
    sourceFocusCopy: 'Arraste um item acima ou use qualquer campo da árvore da esquerda.',
    targetFocusCopy: 'Solte na área que representa o tipo de ligação desejado.',
    manualPathLabel: 'Caminho da origem',
    manualPathPlaceholder: '$.dadosApolice.numeroApolice ou dadosApolice.numeroApolice',
    useAsAlias: 'Usar como origem principal',
    addToConcat: 'Adicionar à composição',
    useAsDefault: 'Usar como valor padrão',
    addFallback: 'Adicionar alternativa',
    mappedEmpty: 'Arraste campos da origem para o destino para começar.',
    clearFieldConfig: 'Limpar configuração do campo',
    advancedLabel: 'Campo avançado (opcional)',
    validationTitle: 'Verificação da estrutura',
    emptySelection: 'Selecione um campo do destino para ajustar a forma de preenchimento.',
    mapFromGuideTitle: 'Como montar um array ligado a outra lista',
    mapFromGuideStep1: 'Crie ou selecione um array no destino.',
    mapFromGuideStep2: 'No campo abaixo, escolha qual lista da origem o backend deve percorrer.',
    mapFromGuideStep3:
      'O [item] desse array representa cada item da lista. Crie os campos filhos dentro dele.',
    mapFromGuideStep4:
      'Arraste os campos do item atual para esses filhos. Se houver outra lista dentro dele, crie outro array e repita.',
    mapFromGuideStep5:
      'Use caminho relativo para o item atual e caminho completo só quando precisar buscar algo fora desse item.'
  },
  rules: {
    panelTitle: 'Regras visuais do campo',
    panelCopy: 'Monte condições e ações de preenchimento sem precisar escrever expressões longas.',
    helper: 'Ao salvar, o sistema transforma isso no formato que o backend precisa ler.',
    assistantCopy: 'Monte a lógica visualmente aqui e o sistema grava isso no campo de destino.',
    empty: 'Nenhuma regra visual criada ainda.',
    createButton: 'Nova regra visual'
  }
} as const;
